### PR TITLE
Unit Tests

### LINKED ISSUE #19: Session Manager breaks in unit testing environments
The Session Manager module currently breaks a lot of other test suites when it's installed, as it incorrectly assumes that a `HTTPRequest` object will always be passed to the `AuthenticationHandler::logIn()` method. I don't think the module can safely operate _without_ the information in the request, so there might be two patches to apply:

- Throwing an Exception when a `HTTPRequest` object isn't passed to `logIn()`, to make the root issue clearer for developers that encounter it in the future
- Disabling the module's custom `AuthenticationHandler`s in test contexts (and explicitly re-enabling them for tests in the module itself)

The full error output:

```
TypeError: Argument 2 passed to SilverStripe\SessionManager\Model\LoginSession::find() must be an instance of SilverStripe\Control\HTTPRequest, null given, called in /project/vendor/silverstripe/silverstripe-session-manager/src/Security/LogInAuthenticationHandler.php on line 66

/project/vendor/silverstripe/silverstripe-session-manager/src/Model/LoginSession.php:132
/project/vendor/silverstripe/silverstripe-session-manager/src/Security/LogInAuthenticationHandler.php:66
/project/vendor/silverstripe/framework/src/Security/RequestAuthenticationHandler.php:63
/project/vendor/silverstripe/framework/src/Dev/SapphireTest.php:1171
/project/vendor/silverstripe/framework/src/Dev/SapphireTest.php:1155
/project/vendor/silverstripe/versioned-admin/tests/Forms/GridField/GridFieldFileRestoreActionTest.php:18
/project/vendor/sminnee/phpunit/phpunit:52
```

### PR DESCRIPTION
**Pull request by bergice**
Resolves https://github.com/silverstripeltd/product-issues/issues/325
Resolves https://github.com/silverstripe/silverstripe-session-manager/issues/19

### CODE REVIEW

File: src/Security/LogInAuthenticationHandler.php [hunk 1]
```diff
@@ -63,6 +64,10 @@ public function authenticateRequest(HTTPRequest $request)
 
     public function logIn(Member $member, $persistent = false, HTTPRequest $request = null)
     {
+        if ($request == null) {
+            $request = Controller::curr()->request;
+        }
```
Comment (Cheddam) [inline src/Security/LogInAuthenticationHandler.php]: This is still unsafe, as Controller::curr() can return `null`. I'd suggest adding a `Controller::has_curr()` check, and throwing an exception describing the reliance on the request object if that check fails.

File: src/Security/LogOutAuthenticationHandler.php [hunk 2]
```diff
@@ -26,6 +27,10 @@ public function logIn(Member $member, $persistent = false, HTTPRequest $request
 
     public function logOut(HTTPRequest $request = null)
     {
+        if ($request == null) {
+            $request = Controller::curr()->request;
+        }
```
Comment (Cheddam) [inline src/Security/LogOutAuthenticationHandler.php]: See the comment on the other Authenticator.

File: tests/php/Control/LoginSessionMiddlewareTest.php [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+    {
+        $session = new Session(['activeLoginSession' => 1]);
+        $request = $this->buildRequestMock('/', [], [], null, $session);
+        $request->method('getIP')->willReturn('192.168.0.1');
+
+        // Log in as member1
+        $member1 = $this->objFromFixture(Member::class, 'member1');
+        Security::setCurrentUser($member1);
+
+        $loginSession = LoginSession::get()->byID(1);
```
Comment (Cheddam) [inline tests/php/Control/LoginSessionMiddlewareTest.php]: Would it make more sense to fetch this via `$member1->LoginSessions()->first();` to ensure the `LoginSession` is related to the `Member`?

File: tests/php/Control/LoginSessionMiddlewareTest.yml [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+  member1:
+    FirstName: 'Andre'
+    Email: 'andre@example.org'
+  member2:
+    FirstName: 'Garion'
+    Email: 'garion@example.org'
+
+SilverStripe\SessionManager\Model\LoginSession:
+  1:
+    ID: 1
```
Comment (Cheddam) [inline tests/php/Control/LoginSessionMiddlewareTest.yml]:
```suggestion
```

File: tests/php/Security/LogInAuthenticationHandlerTest.php [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+
+        $member1 = $this->objFromFixture(Member::class, 'member1');
+        $loginAuthenticationHandler = new LogInAuthenticationHandler();
+        $loginAuthenticationHandler->logIn(
+            $member1,
+            false,
+            null
+        );
+
+        $loginSession = LoginSession::get()->byID(1);
```
Comment (Cheddam) [inline tests/php/Security/LogInAuthenticationHandlerTest.php]: Again, I'm wondering if this makes sense to fetch via the `Member`?

It might also make sense to include an assertion that the LoginSession doesn't exist prior to the `logIn()` call?

File: tests/php/Control/LoginSessionMiddlewareTest.php [hunk 6]
```diff
@@ -0,0 +1,127 @@
...
+
+        $this->assertNull(
+            Security::getCurrentUser(),
+            "Middleware logs user out if session is revoked"
+        );
+    }
+
+    public function testMiddlewareSessionWrongMember()
+    {
+        $session = new Session(['activeLoginSession' => 1]);
```
Comment (Cheddam) [inline tests/php/Control/LoginSessionMiddlewareTest.php]: You can retrieve the ID of the fixture programmatically, rather than hardcoding it:

```suggestion
        $sessionID = $this->idFromFixture(LoginSession::class, '1');
        $session = new Session(['activeLoginSession' => $sessionID]);
```

File: tests/php/Security/LogOutAuthenticationHandlerTest.php [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+{
+    use HttpRequestMockBuilder;
+
+    protected $usesDatabase = true;
+
+    protected static $fixture_file = 'LogOutAuthenticationHandlerTest.yml';
+
+    public function testLogout()
+    {
+        $session = new Session(['activeLoginSession' => 1]);
```
Comment (Cheddam) [inline tests/php/Security/LogOutAuthenticationHandlerTest.php]: You can retrieve the ID of the fixture programmatically, rather than hardcoding it:

```suggestion
        $sessionID = $this->idFromFixture(LoginSession::class, '1');
        $session = new Session(['activeLoginSession' => $sessionID]);
```

File: tests/php/Security/LogOutAuthenticationHandlerTest.yml [hunk 8]
```diff
@@ -0,0 +1,12 @@
+SilverStripe\Security\Member:
+  member1:
+    FirstName: 'Andre'
+    Email: 'andre@example.org'
+
+SilverStripe\SessionManager\Model\LoginSession:
+  1:
+    ID: 1
```
Comment (Cheddam) [inline tests/php/Security/LogOutAuthenticationHandlerTest.yml]:
```suggestion
```

File: tests/php/Service/GarbageCollectionServiceTest.php [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+    ];
+
+    public function testGarbageCollection()
+    {
+        DBDatetime::set_mock_now('2003-08-15 12:00:00');
+
+        $garbageCollectionService = new GarbageCollectionService();
+        $garbageCollectionService->collect();
+
+        $loginSession = LoginSession::get()->byID(1);
```
Comment (Cheddam) [inline tests/php/Service/GarbageCollectionServiceTest.php:39]: This one is a little tougher to do programmatically, so perhaps we can leave it be. A simpler test would check that the total number of LoginSessions goes from 3 to 1, but you'd lose the granular descriptions (which will definitely come in handy if one of the cases breaks.)

**Review by Cheddam — CHANGES_REQUESTED** [review]
Solid start! Have provided a few recommendations, and CI is failing due to some sort of dependency issue, so that'll need addressing before we merge.

File: src/Security/LogInAuthenticationHandler.php [hunk 10]
```diff
@@ -63,6 +64,11 @@ public function authenticateRequest(HTTPRequest $request)
 
     public function logIn(Member $member, $persistent = false, HTTPRequest $request = null)
     {
+        if ($request == null && !Controller::has_curr()) {
+            throw new InvalidArgumentException("No HTTPRequest is provided and there is no controller either.");
+        }
+        $request = Controller::curr()->request;
```
Comment (Cheddam) [inline src/Security/LogInAuthenticationHandler.php]: Couple more suggestions on this logic:

- We should only try to re-fetch the $request object if it isn't provided directly to the method.
- The error message should try to convey what the consequence of the missing request object is
- Prefer using getter methods over directly accessing object properties (the `request` property is `protected`, so this seems only to be working currently because of Silverstripe ✨magic✨)

```suggestion
        // Fall back to retrieving request from current Controller if available
        if ($request === null) {
            if (!Controller::has_curr()) {
                throw new InvalidArgumentException("Authentication with SessionManager enabled requires an active HTTPRequest.");
            }
            
            $request = Controller::curr()->getRequest();
        }
```

File: src/Security/LogOutAuthenticationHandler.php [hunk 11]
```diff
@@ -26,6 +27,11 @@ public function logIn(Member $member, $persistent = false, HTTPRequest $request
 
     public function logOut(HTTPRequest $request = null)
     {
+        if ($request == null && !Controller::has_curr()) {
+            throw new InvalidArgumentException("No HTTPRequest is provided and there is no controller either.");
+        }
+        $request = Controller::curr()->request;
```
Comment (Cheddam) [inline src/Security/LogOutAuthenticationHandler.php]: Same feedback as with the other instance of this logic.

```suggestion
        // Fall back to retrieving request from current Controller if available
        if ($request === null) {
            if (!Controller::has_curr()) {
                throw new InvalidArgumentException("Authentication with SessionManager enabled requires an active HTTPRequest.");
            }
            
            $request = Controller::curr()->getRequest();
        }
```

**Review by Cheddam — CHANGES_REQUESTED** [review]
Pretty happy with this now! One more round of suggestions on the `$request` object fallback, and a CI failure to resolve.

**Review by Cheddam — APPROVED** [review]
